<a href="https://colab.research.google.com/github/MinThuKhant763/machine-learning/blob/main/Pandas_DataFrame_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data = {"Name":["Aung","Mya","Su"],
        "Age":[22,25,20],
        "City":["Yangon","Mandalay","Kalaw"]
        }
df = pd.DataFrame(data)
print(df)

   Name  Age      City
0  Aung   22    Yangon
1   Mya   25  Mandalay
2    Su   20     Kalaw

In [3]:
employee_data = {"EmployeeID":[101,102,103],
                 "Name":["John","Kelvin","Peter"],
                 "Salary":[5000,4300,6700],
                 "FullTime":[True,True,False]
                 }
df = pd.DataFrame(employee_data)
print(df)

   EmployeeID    Name  Salary  FullTime
0         101    John    5000      True
1         102  Kelvin    4300      True
2         103   Peter    6700     False

In [4]:
import numpy as np
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns=["A","B","C"])
print(df)

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [5]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns=["A","B","C"],index=["w","x","y","z"])
print(df)

    A   B   C
w   1   2   3
x   4   5   6
y   7   8   9
z  10  11  12

In [6]:
df.index

Index(['w', 'x', 'y', 'z'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, w to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

In [8]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [9]:
df["A"].unique()

array([ 1,  4,  7, 10])

In [10]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [11]:
df.shape

(4, 3)

In [12]:
df.size

12

In [18]:
df.head(2)

   A  B  C
w  1  2  3
x  4  5  6

In [16]:
df.tail(2)

    A   B   C
y   7   8   9
z  10  11  12